config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"  

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/auth/google_oauth2/callback' => 'sessions#googleauth'

  delete '/logout' => 'sessions#destroy'
  
  resources :appointments
  resources :roles
  resources :comments
  
  resources :users do
    resources :cases, only: [:new, :create, :index]
    resources :appointments, only: [:new, :create, :index]
  end

  resources :cases do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments do 
    resources :comments, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
# http://localhost:3000/


# rails generate model Product name:string description:text

app/models/user.rb
class User < ApplicationRecord
    has_many :cases, ->(user){
        unscope(:where).where(pc:user).or(where(client: user)).or(where(bi:user))
    }

    has_many :appointments, through: :cases



    has_many :comments
    # allows me to see what appointments I've commented on
    has_many :commented_appointments, through: :comments, source: :appointment
    
    enum role: [:program_coordinator, :behavioral_therapist, :client]

    has_secure_password 
    validates :email, :first_name, :last_name, presence: true
    validates_uniqueness_of :email

    def return_last_to_first_name 
        self.last_name + ", " + self.first_name
    end

    def return_initials
        self.first_name[0..1] + "." + self.last_name[0..1]
    end
end

# class User < ApplicationRecord
#     has_many :renders
#     has_many :rendered_appointments, through: :renders, source: :appointments
#   end

#   class appointment < ApplicationRecord
#     has_many :renders
#     has_many :users_rendered, through: :renders, source: :users
#   end
  
#   class render < ApplicationRecord
#     belongs_to :user
#     belongs_to :appointment
#   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end

    def create 
         @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to @user
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    def index
        redirect_if_not_authorized
        @users = User.all
    end

    private
    def user_params 
        params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def display_role 
        content_tag(:h2,"Current Role #{current_user.role.split("_").join(" ").titleize}")
    end
end

app/views/users/index.html.erb
    <div class="row">
    <div class="col-12" style="text-align:center">
    Program Coordinators
    <div>
    <div>
  <div class="row container" >
    <div class="container">

          <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">username</th>
            <th scope="col">Email</th>
            <th scope="col">Total Cases</th>
          </tr>
        </thead>
        <tbody>
            <% User.all.each do |user|%>
                <%if user.role == "program_coordinator"%>
                        <tr>
                          <td><%=user.first_name%></td>
                          <td><%=user.last_name%></td>
                          <td><%= link_to user.username, user_appointments_path(user)%></td>
                          <td><%=user.email%></td>
                          <td><%=user.cases.count%></td>
                        </tr>
                <%end%>
            <%end%>
        </tbody>
      </table>
    </div>
      </div>


        <div class="row">
    <div class="col-12" style="text-align:center">
    Behavioral Therapists
    <div>
    <div>
  <div class="row container" >
    <div class="container">

          <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">username</th>
            <th scope="col">Email</th>
            <th scope="col">Total Cases</th>
          </tr>
        </thead>
        <tbody>
            <% User.all.each do |user|%>
                <%if user.role == "behavioral_therapist"%>
                        <tr>
                          <td><%=user.first_name%></td>
                          <td><%=user.last_name%></td>
                          <td><%= link_to user.username, user_appointments_path(user)%></td>
                          <td><%=user.email%></td>
                          <td><%=user.cases.count%></td>
                        </tr>
                <%end%>
            <%end%>
        </tbody>
      </table>
    </div>
      </div>


        <div class="row">
    <div class="col-12" style="text-align:center">
    Clients
    <div>
    <div>
  <div class="row container" >
    <div class="container">

          <table class="table table-hover ">
        <thead class="thead-dark">
          <tr>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">username</th>
            <th scope="col">Email</th>
            <th scope="col">Active</th>
          </tr>
        </thead>
        <tbody>
            <% User.all.each do |user|%>
                <%if user.role == "client"%>
                        <tr>
                          <td><%=user.first_name%></td>
                          <td><%=user.last_name%></td>
                          <td><%= link_to user.username, user_appointments_path(user)%></td>
                          <td><%=user.email%></td>
                          <td><%=user.cases.count==1 ? "active" : "inactive"%></td>
                        </tr>
                <%end%>
            <%end%>
        </tbody>
      </table>
    </div>
      </div>

app/views/users/new.html.erb
 <div
      class="container"
      style="
        margin-top: 10px;
        width: 28%;
        display: flex;
        flex-direction: column;
        justify-content: center;
      "
    >
      <div class="row align-items-center">
        <div class="col">
          <form style="border: 1px solid rgb(231, 223, 223); padding: 10px;" action="/signup" method="POST">
            <input type="hidden" name="profile_img" value="https://pecb.com/conferences/wp-content/uploads/2017/10/no-profile-picture.jpg"/>
            <h4 style="text-align: center;">720BehavioralHealth</h4>

    <%= form_for(@user, url: '/signup') do |f|%>


        <%= f.label :first_name%>
        <%= f.text_field :first_name, :class=>'form-control'%>
        <br>
        <%= f.label :last_name%>
        <%= f.text_field :last_name, :class=>'form-control'%>
        <br>
        <%= f.label :username%>
        <%= f.text_field :username, :class=>'form-control'%>
        <br>

        <%= f.label :email%>
        <%= f.email_field :email, :class=>'form-control'%>
        <br>

        <%= f.label :password%>
        <%= f.password_field :password, :class=>'form-control'%>
        <br>

        <label>Role</label>
        <br>
        <div class="btn-group dropright">
             <%= f.select :role, options_for_select(User.roles.map{|k,v| [k,k]}), {class:'btn btn-secondary dropdown-toggle'}%>
        </div>
        <br>
        <br>
        <%= f.submit "Submit", :class=>'btn btn-primary', :style => 'justify-content: center;'%>
                    <small
              style="text-align: center;"
              id="emailHelp"
              class="form-text text-muted"
              >By signing up, you agree to our Terms, Data Policy and Cookies
              Policy.</small
            >
    <% end %>
          <div
            style="
              border: 1px solid rgb(231, 223, 223);
              padding: 10px;
              text-align: center;
              margin-top: 15px;
            "
          >
            <p>
              Have an account?
                        <%= link_to "Log In", login_path%>
            </p>
          </div>
                    <div
            style="
              border: 1px solid rgb(231, 223, 223);
              padding: 10px;
              text-align: center;
              margin-top: 15px;
            "
          >
            <p>
                    <%= link_to "Log In With Google", "/auth/google_oauth2"%>
            </p>
          </div>
        </div>
      </div>
      <div style="padding: 10px; text-align: center; margin-top: 15px;">
       <p style="font-size: 12px; color: rgb(205, 207, 207);">&#169; 2020 720BehavioralHealth Made By GERMAN CRUZ</p>
      </div>
    </div>

app/views/users/show.html.erb
  <div class="row container" >
    <div class="container">
          <table class="table">
        <thead >
          <tr>
            <th scope="col">Case #</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Time</th>
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
    <%@user.appointments.each do |a|%>
           <%if a.date.strftime("%d").to_i == Date.today.day.to_i%>
          <tr>
            <th scope="row"><%=a.case.id%></th>
            <td><%=a.case.client.first_name%></td>
            <td><%=a.case.client.last_name%></td>
            <td><%=a.from_time.strftime("%I:%M %p")%> - <%=a.to_time.strftime("%I:%M %p")  %></td>
            <td><%=a.date.strftime("%m/%d/%Y")%></td>
          </tr>
          <%end%>
          <%end%>
        </tbody>
      </table>
    </div>
      </div>