config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"  

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/auth/google_oauth2/callback' => 'sessions#googleauth'

  delete '/logout' => 'sessions#destroy'
  
  resources :appointments
  resources :roles
  resources :comments
  
  resources :users do
    resources :cases, only: [:new, :create, :index]
    resources :appointments, only: [:new, :create, :index]
  end

  resources :cases do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments do 
    resources :comments, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
# http://localhost:3000/


# rails generate model Product name:string description:text

app/models/appointment.rb
class Appointment < ApplicationRecord
    scope :order_by_date, -> {order(date: :DESC, from_to: :DESC)}

    belongs_to :case
    has_many :comments
    # allows me to see who has commented my posts and how many times
    has_many :commented_users, through: :comments, source: :user

    validates :from_time, presence: true
    validates :to_time, presence: true
    validates :date, presence: true
    validate :from_to_error
    validate :overlapping_other_appointments
    validate :exceeded_limited_hours


    def from_to_error
        if self.from_time.strftime("%k:%M") >= self.to_time.strftime("%k:%M") 
            errors.add(:times, "do not make sense. #{self.from_time.strftime("%I:%M %p")} - #{self.to_time.strftime("%I:%M %p")}")
        end
    end

    def overlapping_other_appointments
        self.case.bi.appointments.each do |a|
            if a.date == self.date 
                if (a.from_time.strftime("%k").to_i..a.to_time.strftime("%k").to_i ).cover?(self.from_time.strftime("%k").to_i) || (a.from_time.strftime("%k").to_i..a.to_time.strftime("%k").to_i ).cover?(self.to_time.strftime("%k").to_i)
                    errors.add(:to_time, "#{self.from_time.strftime("%I:%M %p")} - #{self.to_time.strftime("%I:%M %p")} overlaps #{a.from_time.strftime("%I:%M %p")} - #{a.to_time.strftime("%I:%M %p")} ")
                end
            end
        end
    end

    def exceeded_limited_hours
        hours = self.to_time.strftime("%k:%M").to_i - self.from_time.strftime("%k:%M").to_i
        if hours < 2 
            errors.add(:limited_hours, "need at least 2 hours")
        elsif hours > 4
            errors.add(:limited_hours, "cannot go over 4 hours")
        end
    end


    def self.grab_days_of_month
        d = Date.today
        days_in_month = Time.days_in_month(d.month,d.year)
        getfirstdaysofmonth = Date.new(d.year,d.month,1).cwday
        days = ["Sun","Mon","Tues","Wed","Thur","Fri","Sat"]
        dates = days + [nil] * getfirstdaysofmonth + (1..days_in_month).to_a
        dates = dates + [nil]*(49-dates.count)
        return dates
    end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
     before_action :redirect_if_not_logged_in
    def new 
        if params[:case_id] && @case = Case.find_by_id(params[:case_id])
            @appointment = @case.appointments.build
        else
            @appointment = Appointment.new
        end
    end

    def create 
        client_case =  Case.find(params[:appointment][:case_id])
        @appointment = client_case.appointments.build(appointment_params)
        if @appointment.save 
            redirect_to case_appointments_path(@appointment.case)
        else
            render :new
        end
    end

    def index 
        if @object = Case.find_by_id(params[:case_id]) || User.find_by_id(params[:user_id])
            @appointments = @object.appointments.order_by_date
        else 
            @error = "This user does not exist" if params[:case_id]
            @appointments = Appointment.order_by_date
        end
        
    end

    def show
        @appointment = Appointment.find(params[:id])
    end

    private 

    def appointment_params 
        params.require(:appointment).permit(:from_time, :to_time, :date, :case_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

    
end

app/views/appointments/index.html.erb
<div class="row container" >
    <div class="container">
    <% Appointment.grab_days_of_month.each_slice(7) do |week|%>
      <div class="row"style="height:12vh" >
      <%week.map do |date|%>
        <div class="col-sm" style="padding: 10px; border: 1px black solid;">
          <%=date.to_s%>
          <br> 
          <% @appointments.each do |a|%>
            <%if a.date.strftime("%d").to_i == date.to_i%>
                <%= link_to a.case.client.return_initials, appointment_path(a) %>
                <br>
            <%end%>
          <%end%>
        </div>
        <%end%>
      </div>
      <%end%>
    </div>
</div>

app/views/appointments/new.html.erb
 <div class="container">


<%= form_for([@case,@appointment]) do |f| %>
    <%if !@case%>
        <div class="form-group row">
       <label for="inputEmail3" class="col-sm-2 col-form-label">Case</label>
            <div class="col-sm-10">
               <%= f.select :case_id, options_for_select(Case.all.map{|k,v| [k.client.return_last_to_first_name,k.id]}),{}, class: "form-control "%>
            </div>
        </div>
    <%else%>
    <%= f.hidden_field :case_id%>
    <%end%>
      <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Start Time</label>
    <div class="col-sm-4">
    <%= f.time_field :from_time, value: "%H:%M", min: 'hh:mm:ss',max: 'hh:mm:ss',  class: "input-group date form-control"%>
    </div>

        <label for="inputPassword3" class="col-sm-2 col-form-label">End Time</label>
    <div class="col-sm-4">
    <%= f.time_field :to_time, value: "%H:%M", min: 'hh:mm:ss',max: 'hh:mm:ss',  class: "input-group date form-control"%>
    </div>
  </div>

  <div class="form-group row">

  </div>

    <div class="form-group row">
        <label for="inputPassword3" class="col-sm-2 col-form-label">Date</label>
    <div class="col-sm-10">
        <%= f.date_select :date,  class: " form-control"%>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-12", style="text-align:center;">
      <%= f.submit "Create Appointment", class:"btn btn-primary", style: "text-align:center"%>
    </div>
  </div>
<%end%>

app/views/appointments/show.html.erb
  <div class="row container" >
    <div class="container">

          <table class="table">
        <thead >
          <tr>
            <th scope="col">Case #</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Time</th>
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row"><%=@appointment.case.id%></th>
            <td><%=@appointment.case.client.first_name%></td>
            <td><%=@appointment.case.client.last_name%></td>
            <td><%=@appointment.from_time.strftime("%I:%M %p")%> - <%=@appointment.to_time.strftime("%I:%M %p")  %></td>
            <td><%=@appointment.date.strftime("%m/%d/%Y")%></td>
          </tr>
          <tr>
        </tbody>
      </table>

<h2 style="text-align:center">Notes Section</h2>
        <%@appointment.comments.each do |c|%>
          <div class="row" >
                <div class="col-3" style="border: 1px black solid;">
                    <%=c.user.return_last_to_first_name%>
                </div>
                <div class="col-9" style="border: 1px black solid;">
                    <%=c.content%>
                </div>
        </div>
        <%end%>
      <%= form_for Comment.new do |f|%>	
        <%= hidden_field_tag 'appointment_id', @appointment.id%>	
        <label>Add Comment</label>
        <%= f.text_area :content, class: "form-control"%>	
        <br>	
        <%= f.submit "Submit"%>	
    <% end %> 
    </div>
      </div>