config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"  

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/auth/google_oauth2/callback' => 'sessions#googleauth'

  delete '/logout' => 'sessions#destroy'
  
  resources :appointments
  resources :roles
  resources :comments
  
  resources :users do
    resources :cases, only: [:new, :create, :index]
    resources :appointments, only: [:new, :create, :index]
  end

  resources :cases do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments do 
    resources :comments, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
# http://localhost:3000/


# rails generate model Product name:string description:text

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>720BehavioralHealth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" width="100%"href="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTqZXyxyHS_q27LwcDmNhuOIZXVNSgdrA3jNg&usqp=CAU">
<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <style>
      .carousel-item {
        height: 300px;
        overflow: hidden;
        width: 100%;
      }
      .carousel-item img {
        width: 100%;
      }
    </style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div> 
      <% if logged_in?%>

<div class="container" style="height:100vh; max-width: 1170px; color:black;">
  <div class="row" style="background-color:#eceff5; height:8vh; padding-top:10px">
    <div class="col-6" >
  <%= image_tag("logo.png")%>
    </div>
    <!--righthand column-->
    <div class="col-6" >
      <ul class="nav justify-content-end">
        <li class="nav-item">
            <div class="dropdown" >
            <a class="btn  dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hello <%=current_user.first_name%>!
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#">User Account</a>
              <a class="dropdown-item" href="#">Have an idea?</a>
            <%= link_to "All cases", cases_path, class: "dropdown-item"%>
            <%= link_to "All users", users_path, class: "dropdown-item"%>
             <%= link_to "Logout", logout_path, method: "delete", class: "dropdown-item"%>

            </div>
          </div>
        </li>
      </ul>
    </div>
    <!--end righthand column-->
   </div>

    <!--end of first row-->
    <div class="row" style="height:4vh">
      <div class="col-4">

      </div>
      <div class="col-4">
          <%= Time.now.strftime("%A %B %M, %Y")%>
      </div>
      <div class="col-4 ">
      <%if authorized?%>
        <div class="nav justify-content-end">
            <%= link_to new_case_path, :style=>'margin-right: 25px;',:action => 'go' do %>
            New Case <span style="color:blue" class="material-icons">note_add</span> 
            <%end%>
            <%= link_to new_appointment_path, :action => 'go' do %>
                New Appointment <span style="color:blue" class="material-icons"> group_add</span> 
            <%end%>
        </div>
      <%end%>
      </div>
    </div>

    <%= yield %>
  

      <div class="row" style="background-color:#eceff5; height:4vh">
          <div class="col-6">
          <span style="color:blue" class="material-icons">lock_outline</span> locked through: <%=Date.today%> by Staff
            </div>
            <div class="col-6 ">
            <%if authorized?%>
              <div class="nav justify-content-end">
                    <%= link_to user_cases_path(current_user), :style=>'margin-right: 25px;',:action => 'go' do %>
                      <span style="color:blue" class="material-icons">assignment_ind</span> Cases
                    <%end%>
                     <%= link_to user_appointments_path(current_user), :action => 'go' do %>
                        <span style="color:blue" class="material-icons">schedule</span> Appointments
                    <%end%>
              </div>
            <%end%>
            </div>
      </div>
</div>
 
      <%else%>
<%= yield %>
      <%end%>
    </div>
    
    

        <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>